# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 157fe5466b50551ce7394f3a72f8d72bc738d8bd19e3bea28598586377b188f4af56515838a0e2c7e157e8d18389244800a08bb6f56d3491dacead972f88d43d

test:
  secret_key_base: 7d53cdfd9734d1085abaf2f7cb56c846cc4a409fd68ee26b3d22843bc31684de3a4e7d411745fc0a0262acffb1ba63c6be7ba4fab7fe00955431f1518bfd5883

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
